version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.25.2-alpine #swap tag to raspberry to run on a raspberry pi
    volumes:
      - './Data/Vaultwarden:/data'
    restart: on-failure
    environment:
      WEBSOCKET_ENABLED: '${WEBSOCKET_ENABLED}'
      SIGNUPS_ALLOWED: '${SIGNUPS_ALLOWED}'
#      SIGNUPS_DOMAINS_WHITELIST: '${SIGNUPS_DOMAINS_WHITELIST}'
      SIGNUPS_VERIFY: '${SIGNUPS_VERIFY}'
      INVITATIONS_ALLOWED: '${INVITATIONS_ALLOWED}'
      SHOW_PASSWORD_HINT: '${SHOW_PASSWORD_HINT}'
#      ADMIN_TOKEN: '${ADMIN_TOKEN}'
#      DISABLE_ADMIN_TOKEN: '${DISABLE_ADMIN_TOKEN}'

      # Mail Server
#      SMTP_HOST: '${SMTP_HOST}'
#      SMTP_FROM: '${SMTP_FROM}'
#      SMTP_PORT: '${SMTP_PORT}'
#      SMTP_SECURITY: '${SMTP_SECURITY}'
#      SMTP_USERNAME: '${SMTP_USERNAME}'
#      SMTP_PASSWORD: '${SMTP_PASSWORD}'

      # Logging
      LOG_FILE: '/data/vaultwarden.log'
      LOG_LEVEL: '${LOG_LEVEL}'
#      USE_SYSLOG: '${USE_SYSLOG}'
#      EXTENDED_LOGGING: '${EXTENDED_LOGGING}'

      # YubiKey auth1
      YUBICO_CLIENT_ID: '${YUBICO_CLIENT_ID}'
      YUBICO_SECRET_KEY: '${YUBICO_SECRET_KEY}'
      # YubiKey auth2
      YUBICO_CLIENT_ID2: '${YUBICO_CLIENT_ID2}'
      YUBICO_SECRET_KEY2: '${YUBICO_SECRET_KEY2}'

  nginx:
    build: './nginx'
    links:
      - vaultwarden
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
    command: /bin/sh -c "/run_nginx.sh"
    restart: on-failure
    networks:
      default:
    ports:
      - 8484:80

networks:
  default:
    driver: bridge
